# Generated by Django 4.2.4 on 2023-09-10 19:56

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geojsonfile',
            name='geojson',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
