# Generated by Django 4.2.4 on 2023-09-12 23:59

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_geojsonfile_geojson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geojsonfile',
            name='geojson',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
    ]
