# Generated by Django 4.1.13 on 2024-09-12 11:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_share_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
