# Generated by Django 4.2.4 on 2023-10-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rasterfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='rasterfile',
            name='bounds',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='rasterfile',
            name='png',
            field=models.FileField(blank=True, default='', null=True, upload_to='rasters/'),
        ),
    ]
