# Generated by Django 4.2.4 on 2023-10-24 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_rasterfile_png'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rasterfile',
            old_name='bounds',
            new_name='tiles',
        ),
        migrations.RemoveField(
            model_name='rasterfile',
            name='png',
        ),
    ]
