# Generated by Django 4.2.4 on 2023-11-10 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_rename_bounds_rasterfile_tiles_remove_rasterfile_png'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoserverData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('workspace', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('epsg', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('raster', models.ManyToManyField(blank=True, null=True, to='main.rasterfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vector', models.ManyToManyField(blank=True, null=True, to='main.geojsonfile')),
            ],
        ),
    ]
