# Generated by Django 4.2.4 on 2023-11-29 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_rasterfile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vector',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'filename',
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    'format_name',
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ('file', models.FileField(upload_to='vectors/')),
                (
                    'dbname',
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
