# Generated by Django 4.2.4 on 2023-12-12 20:09

from django.db import migrations, models
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_project_name'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='vector',
        #     name='file',
        #     field=models.FileField(upload_to=main.utils.generate_upload_path),
        # ),
    ]
