# Generated by Django 4.1.13 on 2024-01-16 14:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_spatialdatat_alter_vector_file_attributedatat'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialDataT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
        ),
        migrations.AlterField(
            model_name='vector',
            name='file',
            field=models.FileField(upload_to=main.utils.generate_upload_path),
        ),
        migrations.CreateModel(
            name='AttributeDataT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('properties', models.JSONField()),
                ('spatial_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.spatialdatat')),
            ],
        ),
    ]
