# Generated by Django 4.1.13 on 2024-01-18 12:37

from django.db import migrations, models
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_spatialdatat_alter_vector_file_attributedatat'),
    ]

    operations = [
        migrations.AddField(
            model_name='spatialdatat',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rasterfile',
            name='raster',
            field=models.FileField(upload_to=main.utils.generate_upload_path_raster, validators=[main.utils.validate_file_extension]),
        ),
    ]
