# Generated by Django 4.1.13 on 2024-02-15 17:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.utils
from osgeo import gdal

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_rasterfile_png_alter_rasterfile_raster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rasterfile',
            name='bands',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rasterfile',
            name='raster',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['tif', 'tiff']), main.utils.validate_file_size]),
        ),
        migrations.CreateModel(
            name='RasterVisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50)),
                ('png', models.FileField(upload_to=main.utils.generate_upload_path_raster)),
                ('raster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.rasterfile')),
            ],
        ),
    ]
