# Generated by Django 4.1.13 on 2024-03-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_rasterfile_bands_alter_rasterfile_raster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geojsonfile',
            name='group_id',
            field=models.IntegerField(default=0),
        ),
    ]
