# Generated by Django 5.0.4 on 2024-05-31 21:41

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_geojsonfile_group_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Geojson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('attributes', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VectorFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='GeoserverData',
        ),
        migrations.DeleteModel(
            name='Shapefile',
        ),
        migrations.DeleteModel(
            name='SpatialDataT',
        ),
        migrations.RemoveField(
            model_name='project',
            name='vector',
        ),
        migrations.AddField(
            model_name='geojson',
            name='vector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vectorfilemodel'),
        ),
        migrations.DeleteModel(
            name='Vector',
        ),
    ]
