# Generated by Django 5.0.4 on 2024-07-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_geojson_vectorfilemodel_delete_geoserverdata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geojsonfile',
            name='style',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
