# Generated by Django 5.0.4 on 2024-07-11 22:02

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_geojsonfile_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geojsonfile',
            name='style',
            field=models.JSONField(default=main.models.get_default_style),
        ),
    ]
