# Generated by Django 5.0.4 on 2024-07-11 23:38

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_geojsonfile_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geojson',
            name='vector',
        ),
        migrations.AddField(
            model_name='geojson',
            name='style',
            field=models.JSONField(default=main.models.get_default_style),
        ),
        migrations.AddField(
            model_name='project',
            name='vector',
            field=models.ManyToManyField(blank=True, to='main.vectorfilemodel'),
        ),
        migrations.AddField(
            model_name='vectorfilemodel',
            name='format_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vectorfilemodel',
            name='geoms',
            field=models.ManyToManyField(to='main.geojson'),
        ),
    ]
