# Generated by Django 5.0.4 on 2024-07-26 20:43

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_geojson_vector_geojson_style_project_vector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vectorfilemodel',
            name='style',
            field=models.JSONField(default=main.models.get_default_style),
        ),
        migrations.AlterField(
            model_name='geojson',
            name='style',
            field=models.JSONField(default={}),
        ),
    ]
