# Generated by Django 5.0.4 on 2024-07-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_vectorfilemodel_style_alter_geojson_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geojson',
            name='style',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='vectorfilemodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
