# Generated by Django 5.0.4 on 2024-08-17 19:18

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_remove_project_geojson_delete_geojsonfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='vectorfilemodel',
            name='style_type',
            field=models.CharField(choices=[('G', 'Global'), ('C', 'Categorized')], default='G'),
        ),
        migrations.AlterField(
            model_name='geojson',
            name='style',
            field=models.JSONField(default=main.models.get_default_style),
        ),
    ]
