# Generated by Django 5.0.4 on 2024-08-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_vectorfilemodel_style_type_alter_geojson_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vectorfilemodel',
            name='style_type',
        ),
        migrations.AlterField(
            model_name='geojson',
            name='style',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
