# Generated by Django 5.0.4 on 2024-08-23 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_remove_vectorfilemodel_style_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vectorfilemodel',
            name='style',
        ),
    ]
