# Generated by Django 5.1 on 2024-09-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='total_data_usage',
            new_name='total_raster_usage',
        ),
        migrations.AddField(
            model_name='profile',
            name='total_vector_usage',
            field=models.BigIntegerField(default=0),
        ),
    ]
